set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

set-option -g status on
set-option -g status-keys vi
set-option -g status-left "#[fg=green]#S #[fg=yellow]- #[fg=cyan]#I:#W "
set-option -g status-right "%Y-%m-%d %H:%M:%S"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
